spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/spring_db
    username: admin
    password:
    tomcat:
      validation-query: SELECT 1
      test-while-idle: true

  mail:
    host: smtp.yandex.ru
    port: 465
    username: yandex778@yandex.ru
    password:
    protocol: smtps
  sql:
    init:
      mode: always

paypal:
  clientId:
  clientSecret:
vkpay:
  clientId:
  clientSecret:

