spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/spring_db
    username:
    password:
    tomcat:
      validation-query: SELECT 1
      test-while-idle: true

  mail:
    host: smtp.yandex.ru
    port: 465
    username:
    password:
    protocol:
  sql:
    init:
      mode: always
vkpay:
  clientId: 627fdbfa24232a5b62f9c295baa93f7db9752873
  clientSecret: Vb3D0s1OUaPCfR4Pwaeu
paypal:
  clientId: AYorBMEX1pnSw2vIsrEl0h5BmQldeaPlu8KS0mATQvHJ6wra9MT_thFLUQhrwTWP-5VonDWXTMLBToRn
  clientSecret: EFJy1rn2dVRZhZavmmvfCDsJOL_eU_1aeQyx6WIqansdwutGiZqPJ78GtgOkPjvVRmR4jUwHQVdD582s

upload:
  project:
    path: C:/Users/HOME-PC/Desktop/project/projects/
    types: application/pdf,image/png,image/jpeg
  order:
    path: C:/Users/HOME-PC/Desktop/project/orders/
    types: application/pdf,application/msdoc,application/vnd
  image:
    types: image/gif,image/png,image/jpeg

notifies:
  ru:
    welcome:
      title: Добро пожаловать, %s на сервис разработки!
      message: Ваш аккаунт успешно активирован!
    buy:
      title: Оплата прошла успешно!
      message: Посмотреть чек оплаты можно здесь - %s
    info:
      title: Ваш статус заявки изменён!
      message: Перейдите по ссылке - %s для того, чтобы узнать подробней.
    order:
      title: Вы успешно создали заказ!
      message: Ваш заказ сейчас на рассмотрении, в ближайшее время мы свяжемся с вами для уточнения деталей заказа.
server:
  port: 9000
